var esNuevo = false;
var deseaImprimir = true;
var aceptaDescuento = (15 + 18 == 33);
var sonLasListasIguales = (lista1 != lista2);
var lista1 = 100;
var lista2 = 100;
console.log("Este bolean es ", aceptaDescuento);
console.log("ambos boleanos son verdaderos: ", deseaImprimir && aceptaDescuento);
console.log("Las listas son iguales ?", sonLasListasIguales);
var esAlgunaVerdadera = aceptaDescuento || deseaImprimir || sonLasListasIguales;
var sonTodasVerdaderas = aceptaDescuento && deseaImprimir && sonLasListasIguales;
console.log("es alguna verdadera ? : ", esAlgunaVerdadera);
console.log("son todas verdaderas ? : ", sonTodasVerdaderas);
